version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mern-shop-db'
    environment:
      - MONGO_INITDB_DATABASE=mern-shop
      - MONGO_USER=${MONGO_USER}
      - MONGO_PWD=${MONGO_PWD}
    volumes:
    - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    - ./data:/data/db
    ports:
    - '27017:27017'
